namespace ConsoleApp;

public static class Setup
{
    public static void DisplayWelcomeMessage()
    {
        const string border = "*********************************************************************";

        Console.WriteLine("{0}", border);
        Task.Delay(100).Wait();
        Console.WriteLine("{0}", border);
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                                      ...-=++*++-:...            ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                                    .-+*************=:.          ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                                  .=*******************=.        ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                                 :+**********************-.      ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                                  .-***********************-     ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                                     -**********************-    ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                                      .=****+==+************+:   ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                                        :+=.    .-***********=.  ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                                                 .=**********+.  ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                                                .:***********+.  ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                                              ..=************+.  ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                               .:--=++++++++*****************-   ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                             :+*****************************+.   ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Task.Delay(100).Wait();
        Console.Write("                            .+*****************************=.    ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Task.Delay(100).Wait();
        Console.Write("                      ...::...:***************************:      ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                    .-+******+:.:*********************+=.        ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                   .***********: .=***+===========--:            ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                   =************.  ..                            ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                   *************:                                ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                   -***********+                                 ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                    :*********=                                  ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Task.Delay(100).Wait();
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                     .:=+*+=-..                                  ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Console.Write("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Console.Write("                                                                 ");
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("**");
        Console.ForegroundColor = ConsoleColor.Red;
        Task.Delay(100).Wait();
        Console.ForegroundColor = ConsoleColor.White;
        Console.WriteLine("{0}", border);
        Task.Delay(100).Wait();
        Console.WriteLine("{0}", border);
    }
}